import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#333' },
  header: { borderBottom: 2, borderBottomColor: '#16a34a', paddingBottom: 15, marginBottom: 20 },
  companyName: { fontSize: 20, fontWeight: 'bold', color: '#16a34a' },
  policyTitle: { fontSize: 24, textAlign: 'center', marginTop: 10, fontWeight: 'bold', textTransform: 'uppercase' },
  section: { marginTop: 20, padding: 10, backgroundColor: '#f9fafb', borderRadius: 4 },
  sectionTitle: { fontSize: 12, fontWeight: 'bold', borderBottom: 1, borderBottomColor: '#e5e7eb', paddingBottom: 5, marginBottom: 10, color: '#111827' },
  grid: { flexDirection: 'row', flexWrap: 'wrap' },
  gridItem: { width: '50%', marginBottom: 10 },
  label: { fontSize: 8, color: '#666', textTransform: 'uppercase' },
  value: { fontSize: 10, fontWeight: 'bold', marginTop: 2 },
  statusBadge: { position: 'absolute', top: 40, right: 40, padding: '5 10', backgroundColor: '#dcfce7', color: '#166534', borderRadius: 10, fontSize: 10, fontWeight: 'bold' },
  footer: { position: 'absolute', bottom: 40, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#999', borderTop: 1, borderTopColor: '#e5e7eb', paddingTop: 10 }
});

export const PolicyPDF = ({ data }: { data: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.companyName}>TOQUE INSURANCE</Text>
      </View>

      <View style={styles.statusBadge}>
        <Text>{data.status?.toUpperCase() || 'ACTIVE'}</Text>
      </View>

      <Text style={styles.policyTitle}>Insurance Policy Schedule</Text>
      
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Policy Overview</Text>
        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Policy Number</Text>
            <Text style={styles.value}>{data.policyNumber}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Insurer / Provider</Text>
            <Text style={styles.value}>{data.provider}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Policy Type</Text>
            <Text style={styles.value}>{data.type}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Sum Insured / Limit</Text>
            <Text style={styles.value}>₹{data.premiumAmount * 100}</Text>
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Insured Details</Text>
        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Policy Holder</Text>
            <Text style={styles.value}>{data.lead?.clientName}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Contact</Text>
            <Text style={styles.value}>{data.lead?.clientPhone}</Text>
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Period of Insurance</Text>
        <View style={styles.grid}>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Start Date</Text>
            <Text style={styles.value}>{new Date(data.startDate).toLocaleDateString()}</Text>
          </View>
          <View style={styles.gridItem}>
            <Text style={styles.label}>Expiry Date</Text>
            <Text style={styles.value}>{new Date(data.endDate).toLocaleDateString()}</Text>
          </View>
        </View>
      </View>

      <View style={styles.footer}>
        <Text>This policy is subject to the terms and conditions of the insurer. Please keep this document safe.</Text>
        <Text style={{ marginTop: 4 }}>Generated by Toque Insurance Operating System</Text>
      </View>
    </Page>
  </Document>
);
